In [1]:
%matplotlib inline
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
from CKN import *
from Nystrom import *
from image_processing_utils import *
import scipy.optimize
import seaborn as sb
import math
import numpy as np


In [3]:
batch_size=64
test_batch_size=1000

train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=test_batch_size, shuffle=True)


inds=range(60000)
import random
random.seed(2017)
random.shuffle(inds)
test=train_loader.dataset.train_data[inds[:3000],:,:]
X_labels=train_loader.dataset.train_labels[torch.LongTensor(inds[:3000])]




In [4]:
"""
Train a SVM to categorize 28x28 pixel images into digits (MNIST dataset).
"""

import numpy as np


def main():
    """Orchestrate the retrival of data, training and testing."""
    data = get_data()

    # Get classifier
    from sklearn.svm import SVC
    clf = SVC(probability=False,  # cache_size=200,
              kernel="rbf", C=2.8, gamma=.0073)

    print("Start fitting. This may take a while")

    # take all of it - make that number lower for experiments
    examples = len(data['train']['X'])
    clf.fit(data['train']['X'][:examples], data['train']['y'][:examples])

    analyze(clf, data)


def analyze(clf, data):
    """
    Analyze how well a classifier performs on data.

    Parameters
    ----------
    clf : classifier object
    data : dict
    """
    # Get confusion matrix
    from sklearn import metrics
    predicted = clf.predict(data['test']['X'])
    print("Confusion matrix:\n%s" %
          metrics.confusion_matrix(data['test']['y'],
                                   predicted))
    print("Accuracy: %0.4f" % metrics.accuracy_score(data['test']['y'],
                                                     predicted))

    # Print example
    try_id = 1
    out = clf.predict(data['test']['X'][try_id])  # clf.predict_proba
    print("out: %s" % out)
    size = int(len(data['test']['X'][try_id])**(0.5))
    view_image(data['test']['X'][try_id].reshape((size, size)),
               data['test']['y'][try_id])


def view_image(image, label=""):
    """
    View a single image.

    Parameters
    ----------
    image : numpy array
        Make sure this is of the shape you want.
    label : str
    """
    from matplotlib.pyplot import show, imshow, cm
    print("Label: %s" % label)
    imshow(image, cmap=cm.gray)
    show()


def get_data():
    """
    Get data ready to learn with.

    Returns
    -------
    dict
    """
    simple = False
    if simple:  # Load the simple, but similar digits dataset
        from sklearn.datasets import load_digits
        from sklearn.utils import shuffle
        digits = load_digits()
        x = [np.array(el).flatten() for el in digits.images]
        y = digits.target

        # Scale data to [-1, 1] - This is of mayor importance!!!
        # In this case, I know the range and thus I can (and should) scale
        # manually. However, this might not always be the case.
        # Then try sklearn.preprocessing.MinMaxScaler or
        # sklearn.preprocessing.StandardScaler
        x = x/255.0*2 - 1

        x, y = shuffle(x, y, random_state=0)

        from sklearn.cross_validation import train_test_split
        x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                            test_size=0.33,
                                                            random_state=42)
        data = {'train': {'X': x_train,
                          'y': y_train},
                'test': {'X': x_test,
                         'y': y_test}}
    else:  # Load the original dataset
        from sklearn.datasets import fetch_mldata
        from sklearn.utils import shuffle
        mnist = fetch_mldata('MNIST original')

        x = mnist.data
        y = mnist.target

        # Scale data to [-1, 1] - This is of mayor importance!!!
        x = x/255.0*2 - 1

        x, y = shuffle(x, y, random_state=0)

        from sklearn.cross_validation import train_test_split
        x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                            test_size=0.33,
                                                            random_state=42)
        data = {'train': {'X': x_train,
                          'y': y_train},
                'test': {'X': x_test,
                         'y': y_test}}
    return data


if __name__ == '__main__':
    main()


/Users/cdonnat/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Start fitting. This may take a while
Confusion matrix:
[[2258    1    4    1    2    2    3    1    4    2]
 [   1 2566    9    1    1    0    0    7    3    0]
 [   4    1 2280    5    4    0    1    9    8    2]
 [   0    0   14 2304    1   13    0    6    8    2]
 [   2    2    2    0 2183    0    7    5    0   10]
 [   4    0    0   16    3 2026   12    1    4    3]
 [   7    5    3    0    5    2 2245    0    4    0]
 [   1    6   11    2    5    1    0 2373    5   13]
 [   3    9    4    9    4   10    2    3 2166    5]
 [   3    2    2    6   19    6    0   12   10 2329]]
Accuracy: 0.9840


ValueError: Expected 2D array, got 1D array instead:
array=[-1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -0.89803922 -1.         -0.81960784 -0.96862745
  0.6         0.98431373  0.69411765  0.89019608  0.6         0.09803922
 -0.94509804 -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -0.85098039 -0.55294118  0.62352941  0.3254902
  0.83529412  0.00392157  0.98431373  0.97647059  0.97647059  0.97647059
  0.98431373  0.68627451  0.16862745 -0.16078431 -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -0.85098039  0.09803922  0.97647059
  0.98431373  0.97647059  0.97647059  0.97647059  0.98431373  0.97647059
  0.97647059  0.97647059  0.98431373  0.97647059  0.97647059  0.97647059
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.
 -0.16078431  0.97647059  0.97647059  0.98431373  0.97647059  0.97647059
  0.97647059  0.98431373  0.97647059  0.28627451  0.49019608  0.98431373
  0.97647059  0.97647059  0.97647059 -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -0.8745098   0.69411765  0.98431373  0.98431373  1.
  0.98431373  0.98431373  0.00392157 -0.10588235 -0.30980392 -1.         -1.
 -1.         -0.40392157  0.74901961  0.98431373 -0.50588235 -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -0.77254902  0.97647059  0.97647059  0.97647059
  0.98431373  0.78039216  0.82745098 -0.82745098 -1.         -1.         -1.
 -1.         -1.         -1.          0.54509804  0.97647059 -0.11372549
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -0.77254902  0.97647059
  0.97647059  0.97647059  0.61568627 -0.06666667 -0.70980392 -1.         -1.
 -1.         -1.         -1.         -1.         -1.          0.54509804
  0.97647059  0.25490196 -0.48235294 -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.
 -0.96862745  0.39607843  0.97647059  0.97647059 -0.11372549 -1.         -1.
 -1.         -1.         -1.         -1.         -0.6        -0.10588235
 -0.11372549  0.74117647  0.97647059  0.98431373  0.1372549  -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -0.55294118  0.98431373  0.98431373  0.99215686
  0.78823529  0.10588235  0.10588235  0.10588235  0.10588235  0.39607843
  0.98431373  0.99215686  0.98431373  0.98431373  0.98431373  0.10588235
 -0.23921569 -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -0.85098039
  0.49019608  0.97647059  0.98431373  0.97647059  0.97647059  0.97647059
  0.98431373  0.97647059  0.97647059  0.97647059  0.98431373  0.97647059
  0.97647059  0.97647059  0.30196078 -0.05098039 -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -0.85098039  0.81176471  0.98431373  0.97647059
  0.97647059  0.97647059  0.98431373  0.97647059  0.97647059  0.97647059
  0.98431373  0.97647059  0.97647059  0.97647059  0.89019608 -0.34117647
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -0.01176471
  0.95294118  0.98431373  0.97647059  0.97647059  0.97647059  0.98431373
  0.97647059  0.97647059  0.97647059  0.89019608  0.09019608  0.38823529
  0.97647059  0.98431373  0.73333333 -0.80392157 -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -0.74901961  0.79607843  0.98431373  0.99215686  0.98431373  0.91372549
  0.37254902  0.38039216 -0.01960784 -0.30196078  0.27843137  0.18431373
 -1.         -1.         -1.          0.99215686  0.98431373 -0.56078431
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -0.55294118  0.97647059  0.97647059
  0.98431373  0.09019608 -0.56078431 -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.          0.78823529
  0.97647059  0.01960784 -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -0.55294118
  0.97647059  0.97647059  0.81176471 -0.85098039 -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
  0.10588235  0.97647059  0.83529412 -0.82745098 -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.
 -0.55294118  0.97647059  0.97647059  0.96078431 -0.41176471 -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -0.6         0.89019608  0.97647059  0.38823529 -0.97647059 -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -0.01176471  0.96078431  0.99215686  0.59215686 -0.08235294
 -0.8745098  -1.         -1.         -1.         -1.         -1.
 -0.64705882  0.10588235  0.89019608  0.99215686  0.9372549   0.86666667
 -0.80392157 -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.          0.76470588
  0.98431373  0.97647059  0.97647059  0.00392157 -0.05882353  0.12941176
 -0.55294118  0.23137255  0.3254902   0.76470588  0.97647059  0.97647059
  0.98431373  0.34117647 -0.70196078 -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -0.21568627  0.98431373  0.97647059  0.97647059  0.97647059
  0.98431373  0.97647059  0.97647059  0.97647059  0.98431373  0.97647059
  0.97647059  0.97647059  0.81176471 -0.85098039 -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -0.28627451  0.68627451
  0.97647059  0.97647059  0.98431373  0.97647059  0.97647059  0.97647059
  0.59215686  0.18431373 -0.09019608 -0.68627451 -0.80392157 -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.         -1.         -1.         -1.
 -1.         -1.         -1.         -1.        ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.